### ISSUE TITLE
Cannot get proposalStep to actually finish

### ISSUE THREAD

**Issue by ghost** [human-nature-lab/breadboard-experiments#2]
Hi,

I am making an experiment using the Ultimatum game code as a base, and cannot get my main "step" to finish running, so that it can move on to its "done" step. I have the same problem with the Ultimatum game code itself; it never moves on to perform proposalStep.done(). How can I get it to run the done step?

**Comment by disperse** [comment]
Closing this as an old issue.

If you're still having trouble with this or other aspects of your experiment ping me on gitter:

https://gitter.im/breadboard-help/Lobby
